# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  galleryapi:
    image: galleryapi
    build:
      context: .
      dockerfile: GalleryAPI/Dockerfile
    ports:
      - 5229:8080
